package:
  type: app
  name: pixswap
  label: Pisxwap
  description: Puzzles api
  version: 1.1.1
  dependencies: []
application:
  use_store: true
  plugins:
    - name: common
      plugins:
        - name: database
          type: mariadb
      bindings:
        - name: puzzle-base
          type: migration
          data_version: '1.0.2'
